# This is a basic workflow to help you get started with Actions

name: Events-memorizer

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          apt-get update && apt-get install -y \
          binutils \
          gdal-bin \
          python3-gdal \
          libgdal-dev \
          libproj-dev
      - name: Test
        run: |
          python manage.py test
